// AUTHENTICATION TYPES
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const FETCH_USER = 'FETCH_USER';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// DISCOVER TYPES
export const DISCOVER_START = 'DISCOVER_START';
export const DISCOVER_FAIL = 'DISCOVER_FAIL';
export const DISCOVER_NEAR = 'DISCOVER_NEAR';
export const DISCOVER_NEW = 'DISCOVER_NEW';

// PROFILE TYPES
export const PROFILE_START = 'PROFILE_START';
export const PROFILE_FAIL = 'PROFILE_FAIL';
export const PROFILE_FETCH = 'PROFILE_FETCH';
